source "https://rubygems.org"

gem "jekyll", "~> 3.9", ">= 3.9.0"
gem "jekyll-theme-architect", "~> 0.1", ">= 0.1.1"
gem "kramdown-parser-gfm", ">= 1.1.0"
gem 'nokogiri', '~> 1.10'
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15", ">= 0.15.1"
  gem 'jekyll-paginate', '~> 1.1'
end
